### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by reense** [cklmercer/laravel-model-settings#15]
Hello,

are you planning on adding laravel 8 support any time soon? 👍

**Comment by pktharindu** [comment]
Please add via #16

**Comment by metalmini** [comment]
@pktharindu when will that branch be merged?

**Comment by metalmini** [comment]
@cklmercer any idea when that PR be merged and tagged?

**Comment by pktharindu** [comment]
Ping @cklmercer 😅

**Comment by cklmercer** [comment]
@pktharindu thanks for the ping. I'll update my notifications 😓

**Comment by cklmercer** [comment]
https://github.com/cklmercer/laravel-model-settings/pull/16
