### ISSUE TITLE
how to set multi variables?

### ISSUE THREAD

**Issue by wangjacsi** [cklmercer/laravel-model-settings#3]
Hi, this is really simple and nice. 

I want to use this to my system.

I have questions.

Is there any solution to set multiple variables?

and can we set default values? 

anyway thanks.

**Comment by cklmercer** [comment]
Thanks!

You can set default settings by adding a `$defaultSettings` property to your model.

e.g.
```
class User extends Model {
    protected $defaultSettings = [
        'homepage' => '/dashboard',
        'some-other-setting' => 'random value'
    ];
}
```

and you can set multiple settings at one time by doing something like the following...

```
$user = User::first();

$user->settings()->set([
    'homepage' => '/dashboard',
    'some-random-setting' => 'any value you want'
]);
```

Let me know if this works for you.
