### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by tharindu-abans** [cklmercer/laravel-model-settings#9]
Please make a new release with Laravel 6 support.

**Comment by pmochine** [comment]
#10

**Comment by cklmercer** [comment]
https://github.com/cklmercer/laravel-model-settings/releases/tag/1.3.0

**Comment by pmochine** [comment]
@cklmercer Could you please update https://packagist.org/packages/cklmercer/laravel-model-settings (And set the update automatically)

**Comment by cklmercer** [comment]
updated. will check for automatic update setting
